CXXFLAGS = -D_DEFAULT_SOURCE -D__GLIBC_USE_LIB_EXT2=0
LDFLAGS = $(CXXFLAGS)

dnsseed: dns.o bitcoin.o netbase.o protocol.o db.o main.o util.o
	g++ -pthread $(LDFLAGS) -o dnsseed dns.o bitcoin.o netbase.o protocol.o db.o main.o util.o -lcrypto

%.o: %.cpp *.h
	g++ -std=c++11 -pthread $(CXXFLAGS) -Wall -Wno-unused -Wno-sign-compare -Wno-reorder -Wno-comment -c -o $@ $<
CXXFLAGS += -D_DEFAULT_SOURCE -D__GLIBC_USE_LIB_EXT2=0
